---
title: "Paper 1: Triangulating trends in inequality around the world from secondary databases"
format: html
---

::: {.callout-note collapse="true" appearance="minimal"}
### Load packages

```{r}
library(tidyverse)
library(knitr)
library(data.table)

```
:::

What has happened to within-country inequality globally?

Different headlines - WID suggests general rise (find a quote). PIP much more mixed... even a fall.

Which world we live in matters for how we think we should tackle inequality.

A secular, general rise - suggesting global forces, perhaps something intrinsic to capitalism (Piketty, 2014).

A mixed picture of inequality around the world suggests reflect specific circumstances, with accordingly much more scope for national policy to influence.

Both are reasonable methods and have strengths and weaknesses.

I want to:

a\) Triangulate the key stylized facts. Which observations are robust to across available datasets with their different methods, and which are contingent?

b\) Untangle which methods, definitions affect the different conclusions arrived at.

# Methods and data

## Data sources

### PIP

### WID

### LIS


### Coverage

Give an overview of coverage in each dataset.


## Comparing databases

### Comparing metrics

Does it make a difference whether we look at Gini or top 10%?

People worry about whether Gini masks what's happening at the top.

Empirically: 
    - Make a linear model of top 10% on Gini, for each source separately
    - Make predicted top 10%
    - Take a look at the R2
    - Investigate individual countries with very poor predictions

Sub-Saharan Africa: example where the Gini fell in more cases than the top 10%.

### Since 1990


Similarities:

Convergence – Smaller rises in coutries that started out with high inequality. Driven regionally. (We could do a test for this.)

Indeed for some regions very similar picture:

    - MENA - Roughly 2 point fall, both Gini and top 10%. Only one country with a rise: Not total agreeement on coverage (one country either side)

    - South and South East Asia – Very similar not weighting by population. But wildly different when weighting by population, due to the much much stronger rise

    -  Sub-Saharan Afric – Very similar across sources. Top 10: Roughly even mix of rises and falling countries, but with a 3 point fall on average. Gini: More falls, 5 point on average. (Mention data quality issues: e.g. Kenya big fall. Lesoto big fall. But how comparable are the surveys?? Same surveys underlie WID...)

    - Western Europe – Rises in a majority of countries, but relatively moderate of 1-2 points (Whether Gini of top 10).


Differences:

Verry different bottom line at the global level:

- PIP: roughly equal numbers falling and rising. 0 average change – though a modest rise when pop weighted (2 points). Same whether Gini or Top 10. That's without LAtin America (Which WID is missing). Includung LatAm tips nudges it (with about a 1 point fall unweighter and 1 point rise weighted)

- WID: Far more countries with rising inequality. On average a 3 point rise (whether top 10 or Gini) – [Better to express these relative to the level of ineq. i.e. % increase rather than % point increase? A point rise means 'less' in WID terms because inequality levels are much higher.] But the most stark difference comes when we weight by population. Some key populous countries: India, China, US?, Indonesia? Russia 

That difference is driven by particular regions:
- 


More countries with rises. LArger rises. Especially larger populations. Average view very different:





Countries where the sources paint a radically different picture that affect the aggregate results:

- India: Insane rise in WID 34->56
- China:
- Russia: Massive drop in PIP. Insane rise in WID.
- USA: Much larger rise in WID.

What explains the different trends in these countries? (We can maybe look in more detail, at different welfare concepts etc.)

It sometimes goes the other way: Indonesia – Rise in PIP, fall in WID.

:::

#### Method 2: Use a regression to obtain the time trend



### Results for a range of inequality metrics


::: {.callout-note collapse="true" appearance="minimal"} 
## Calculations for comparisons



## Explaining differences between PIP and WID data

### For a subset of countries we can bridge between the PIP and WID data

Besides the underlying data sources, there are many differences between what is being measured in the PIP and WID data - notably the welfare concept and unit of analysis/equivalization.

In order to get a better understanding of where differences between the datasets arise, for a subset of countries we can bridge between the two somewhat. For example:

-   WID has post-tax income series for some countries
-   We can use LIS to look at how changing the welfare concept, unit of analysis, equivalisation affects things. (For equivalisation, we could also possibly use the newly available PIP harmonized microdata).

### More in-depth discussion of particular outliers

-   Russia is a very notable case where the two datasets tell very different stories.

# Conclusion
