project:
  type: website
  


website:
  title: "personal_site"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Test"
        contents:
          - index.qmd
          - site/shiny_app1/index.html
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



