project:
  type: website
  execute-dir: file

website:
  title: "Joe Hasell"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "DPhil: Triangulating the key facts about global income distribution"
        contents:
          - section: "Papers"
            contents:
              - PhD_pages/paper_pages/overview.qmd
              - PhD_pages/paper_pages/paper1.qmd
              - PhD_pages/paper_pages/paper3.qmd
              - PhD_pages/paper_pages/test_page.qmd
          - section: "Data appendices"
            contents:
              - PhD_pages/data_appendices/1_A_prepare_PIP_and_WID.qmd
              - PhD_pages/data_appendices/1_B_within_country_trends.qmd
              - PhD_pages/data_appendices/3_A_prepare_KLEMS.qmd
              - PhD_pages/data_appendices/3_B_prepare_OECD.qmd
      - section: "About this site"
        contents:
          - how_to.qmd
          - test_pages/test_passing_r_to_python.qmd
          - test_pages/test_with_shinylive.qmd
          - test_pages/test_with_iframe_shiny.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



