project:
  type: website
  execute-dir: project

website:
  title: "Joe Hasell"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "DPhil: Triangulating the key facts about global income distribution"
        contents:
          - PhD_pages/paper_pages/overview.qmd
      - section: "About this site"
        contents:
          - how_to.qmd
          - test_pages/test_with_shinylive.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



