project:
  type: website
  execute-dir: file

website:
  title: "Joe Hasell"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "DPhil: Triangulating the key facts about global income distribution"
        contents:
          - PhD_pages/overview.qmd
          - section: "Paper 1: A global view on inequality within countries"
            contents:
              - PhD_pages/Paper_1/paper1.qmd
              - section: "Data appendices"
                contents:
                  - PhD_pages/Paper_1/data_appendix/1_A_prepare_PIP.qmd
                  - PhD_pages/Paper_1/data_appendix/1_B_prepare_WID.qmd
                  - PhD_pages/Paper_1/data_appendix/1_C_prepare_LIS.qmd
                  - PhD_pages/Paper_1/data_appendix/1_D_prepare_population.qmd
                  - PhD_pages/Paper_1/data_appendix/1_E_prepare_region_classifications.qmd
                  - PhD_pages/Paper_1/data_appendix/1_F_within_country_trends.qmd
      - presentations.qmd
      - section: "About this site"
        contents:
          - how_to.qmd
          - section:
            contents:
              - test_pages/test_passing_r_to_python.qmd
              - test_pages/test_with_shinylive.qmd
              - test_pages/test_with_iframe_shiny.qmd
              - test_pages/test_with_ipywidgets.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



