---
title: "Presentations"
format: html
---

### From $1.90 to $2.15: the updated International Poverty Line
20/01/2023
Department for Social Policy, University of Oxford

A presentation given to Masters students in Comparative Social Policy at the Department for Social Policy, University of Oxford.

[Slides](other_presentations/DSPI_CSP_masters_Jan2023/DSPI_CSP_masters_Jan2023.qmd)


### Triangulating a global view on inequality from secondary data sources
16/02/2023
Institute for New Economic Thinking, University of Oxford

:::{.callout collapse="true"}
## Abstract

Many of the key questions and debates of our time necessitate a global view of economic inequality. Thanks to the development and continued expansion of key global databases of harmonised distributional data, we are in a better position than ever to take such a global view.

And yet, on a range of basic questions concerning the nature and evolution of inequality around the world, there is surprisingly little consensus or clarity. Available global datasets offer starkly differing or even contradictory views. The variety of methods, concepts, and sources adopted in different global databases makes it difficult to interpret and synthesise the insights they offer. Despite the wealth of data available, our view of inequality around the world remains highly fragmented.

To help address this, I line up results from three key global datasets on inequality: the World Inequality Database, the World Bank’s Poverty and Inequality Platform and the Luxembourg Income Study. In doing so, I try to triangulate a more cohesive and comprehensive global view of inequality – drawing together those stylised facts that are robust to choices of data source and methodology; highlighting those that are contingent on such choices; and helping to unpick the reasons for such discrepancies.

:::

[Interactive slides](PhD_pages/Paper_1/Presentation_INET_16_feb_inequality_around_the_world.qmd)

