---
title: "Paper 1: Triangulating trends in inequality around the world from secondary databases"
format: html
bibliography: references_export_2023-04-04.bib
execute:
  echo: false
  warning: false
---

::: {.callout-note collapse="true" appearance="minimal"}
### Load packages and data

```{python}

from plotnine import *
import plotly.express as px
import pandas as pd
import numpy as np
from IPython.display import display, HTML, IFrame, Markdown
import dataframe_image as dfi
import imgkit

from wrangling_and_plotting_functions import *

pd.set_option('display.max_rows', None)

```


```{python}

fp = 'data_appendix/data/clean/pip.csv'
        
df_pip = pd.read_csv(fp)


fp = 'data_appendix/data/clean/wid.csv'

df_wid = pd.read_csv(fp)

fp = 'data_appendix/data/clean/lis.csv'

df_lis = pd.read_csv(fp)


fp = 'data_appendix/data/clean/region_mapping.csv'

df_regions = pd.read_csv(fp)


fp = 'data_appendix/data/clean/population.csv'

df_pop = pd.read_csv(fp)

fp = 'data_appendix/data/clean/region_population.csv'

df_pop_regions = pd.read_csv(fp)


# Gather data into dictionary
source_dfs = {
    "PIP": df_pip,
    "WID": df_wid,
    "LIS": df_lis
    }


# This specifies the +/- for the 'stable' category in the tables below
tolerance_lookup =  {
                'var_search_term': [
                    'Gini',
                    'Top 1pc share', 
                    'Top 10pc share',
                    'Bottom 50pc share'],
                'var_tolerance': [
                    1,
                    1,
                    1,
                    1
                ]
            }

```


```{python}
def make_selection_msg(reference_vals,max_dist_from_refs,all_metrics_requirement,selected_vars):
    msg = f'{reference_vals[0]} vs {reference_vals[1]} (+/- {max_dist_from_refs} years)'

    if len(selected_vars)>1:
        if all_metrics_requirement:
            msg = f'{msg} – Matched countries only'
        else:
            msg = f'{msg} – All available countries' 

    return(msg)

```

:::

READING LIST:
Bourguignon (2015)
The share of wages in total GDP declined in a majority of countries
(91 out of 133 with data) from 1995 to 2014 (ILO, 2016).

 Other authors
question the pre-eminence of globalization as the main driver of global inequality, noting
that inequality trends differ across countries at similar levels of development and that
are equally exposed to trade (Ravallion, 2018; Corlett, 2016). Ravallion (2018) stresses
the vital role that natio

Key point:  the share of income going to both the top 1 per cent and the bottom 50 per
cent has increased in many countries in recent decades. 


In 2021, while the very richest individuals buy trips to space, roughly three billion people are unable to afford a healthy diet. Even  rich countries secured COVID vaccines for their entire population, low-income had barely begun. COVID vaccination rates  at all, the richest countries had already administered more than one dose for every citizen.

Such 



"Inequality defines our time," states the UN Secretary-General.^[United Nations Secretary-General António Guterres made the comment in the 18th Nelson Mandela Annual Lecture in July 2020. See https://www.nelsonmandela.org/news/entry/annual-lecture-2020-secretary-general-guterress-full-speech.]


Just as the demand for data to monitor inequality globally is greater than ever, so is its supply.

In part, this increased concern is a reflection of events - of the severe and uneven impacts of the 2007-8 Global Financial Crisis, the COVID-19 pandemic and recent sharp rises in the cost of living.


# Introduction

Economic inequalities around the world are enormous. As the very richest individuals buy trips to space, roughly three billion people are unable to afford a healthy diet. 

Such stark disparities have gained more attention in recent decades, among policimakers, academics and the public alike. "Inequality defines our time," according to the UN Secretary-General.^[United Nations Secretary-General António Guterres made the comment in the 18th Nelson Mandela Annual Lecture in July 2020. See https://www.nelsonmandela.org/news/entry/annual-lecture-2020-secretary-general-guterress-full-speech.]

In part at least, this increased concern reflects an increase in the *availability* of distributional data. New and expanded sources of data have shed new light on extent of inequality around the world and how it is changing. This has enabled concerns about high or rising inequality to be expressed in new ways, formulated more precisely and subsequently monitored. The supply and demand for global data on inequality have been mutually reinforcing.

Two sources of data have been particularly impactful in this regard: the World Bank's harmonized collection of household survey data, published online through its [*Poverty and Inequality Platform (PIP)*](https://pip.worldbank.org/); and the collection of inequality estimates – most notably top income shares – brought together at the [*World Inequality Database (WID)*](https://wid.world/).^[EDIT: PIP used to be Povcal. It draws upon the work of various regional teams. WID used to be WTID.]

These two sources are the only regularly-updated databases providing global coverage on a relatively consistent basis.^[EDIT: Both datasets suffer important limitations with respect to comparability acrosss time and location. These will be discussed in the data section below. Both datasets, however, take significant steps to harmonize, *ex-post*, the available underlying data. In this respect they can be distinguished from databases such as WIID and SWIID [@atkinson_promise_2001]] Both have played substantial agenda-setting roles in academic research, policy and public debate.

Given its extensive coverage of low- and middle-income countries, the World Bank data occupies a central place in international development policy and research. Most notably, the data is relied on by the UN to set and monitor progress towards many of the targets included within Sustainable Development Goals. It has also to date underpinned the majority of academic studies on inequality that take a global view.^[[Including @Kanbur2022-lk; @lakner_global_2016; @anand_global_2015; @Nino-Zarazua2017-tv; @Ravallion2014-mk] TODO: Check and more refs].

The *WID* database emerged as institutional focal-point to host and coordinate inequality estimates produced as part of the burgeoning literature on top incomes [@atkinson_top_2014; @piketty_capital_2014; @alvaredo_top_2013]. This development of this data has opened new avenues for the study of inequality right across the social sciences (TODO: example refs), underpinning a significant re-evaluation of its causes and consequences [@alvaredo_top_2013]. It has also surely had a substantial impact on the public's conception of inequality, contributing to the momentum generated by the Occupy movement and its framing of inequality in terms of 'the 1%' vs the '99%''.

#### Two worlds of inequality measurement

The two . They in some sense represent *two different worlds* of inequality measurement.

In terms of methods, source, conception of inequality and research questions. "The 1 %" – pretax, with many assumptions needed to get to national income. These come as a bundle. Although both institutions continue to take many steps to provide transparency and reproducibility to their estimates, they remain a black box.

Also in the research questions the datasets aim at. Capital vs labour share. .– including fundamental laws of capitalism with regard to capital accumulation (Piketty) – 

Most crucially, the worlds also diverge in terms of headline messages as to inequality around the world. Contradictory messages emerge concerning the most basic descriptions from the two databases.

They differ as to how ubiquitous a phenomenon rising inequality is around the world. The view from *World Inequality Database* and its associated global report is that inequality is rising in 'nearly everywhere' [@alvaredo_world_2018; @chancel_world_2021].[^WID_quotes] In contrast, the World Bank data and its biannual report offers a much more mixed picture – in which inequality is rising and falling in roughly equal numbers of countries.


[^WID_quotes]:
    > Income and wealth inequalities have been on the rise nearly everywhere since the 1980s, following a series of deregulation and liberalization programs which took different forms in different countries. [@chancel_world_2021, pp. xx]

    > In recent decades, income inequality has increased in nearly all countries, but at different speeds... [@alvaredo_world_2018, pp. xx]


Secondly, the two worlds differ in their conception of global inequality....  decompositions of global inequality into between- and within-country components. (Explain


Incredible efforts, involving the work of hundreds of researchers. Both datasets have continued to improve adn expand. In terms of data availability we are thus in a better position than ever to take a global viw on inequlity. And yet, amidst this wealth of data, limited understanding of very basics concerning inequality around the world.

There remains fundamental ambiguity surrounding which of two possible worlds we live in. 

The '*WID* world' rising inequality within countries has been an almost universal phenomenon. suggests the winners from globalization and economic growth overwhelmingly have been a global elite. It sees the bulk of global inequalities as lying within nations, but emphasises global factors in terms of causes and hence the need for international coordination to combat inequality.

The '*PIP* world' – within-country inequality trends in recent decades have been mixed, and the differences in average incomes between countries remain the lion's share of the globally.As such the importance of national policy (Ravallion, 2018; Corlett, 2016). access to both produced and human capital.

Knowing which of these worlds we live in matters a great deal – for our understanding of inequality today, how it has changed, and also where efforts to combat inequality in the future are likely to be most successful.

Many methodolodical choices concerning underlying data sources, the constraints on temporal coverage this gives rise to,  adjust, conception of inequality. These to some extent come bundled together when making the choice between PIP and WID.


In many particular contexts There are known strengths and weaknesses. However in using the datasets a global view on inequality, requires choosing between methodological 'bundles' whose relative strengths and weaknesses, applied globally, are not well understood.

### Connecting the two worlds
*(In this section I will explain the plan for the paper)*


What we can do is triangulate


In this paper, I focus on trends in within-country inequality in recent decades.(In a companion paper, I look at the global distribution.) I line up what I can. I triangulate what we know – What is true irrespective of which 'world' we consider. And Identify what we don't know – the remaining differences – and try to pinpoint where the differences lie.


I do so with respect to two separate time periods, chosen to tradeoffs with respect to global coverage. The first period – from the fall of the Berlin wall. Driven primarily to the steep drop off in availability before this in household survey data collected in PIP.


This maximises global coverage – 100 countries covering roughly 90% of the world poplation. The downside is that this period misses out – transition, liberalisation and structural adjustment. Question begging, by avoiding specifically the period where inequality thought to rise.

To address this, I analyse a second, longer period extending back to roughly 1980.

Explain approach. (Including LIS – which is close to PIP world (indeed PIP takes data from LIS for a number of high income countries.))

(SUMMAR OF FINDINGS)


## Methods and data

### Concepts of global inequality

Adapted three concepts.

### Data

#### PIP

#### WID




#### LIS

Will be used for income concept. i.e. it represents the PIP world – indeed LIS is the source for PIP for a number of high income countries. But the access to microdata allows us to ask more questions for a subset of countries.

#### Coverage and lining-up observations

(Coverage chart - overlayed 3/5 year)


## Results

### Comparison of typical indicators

- Relative change WID 1% and PIP Gini


### Aligning indices

- Show that measure doesn't matter for WID until top 1 (check Palma ratio)

- Check out how much different metrics matter for PIP.





-----

### Aligning coverage 



## Comparing inequality trends

The focus of this paper is on trends. But worth pointing out levels. Inequality is much higher in WID than in PIP. 

Again this relates to many things – pretax vs disposable income/consumption. Later we will try lining up income concepts more closely. But for global coverage we have to pull together these 'worlds' that combine many differences.


What we're trying to do with triangulation is see whether they show a qualitively similar picture of whether, and how rapidly, inequality was rising or falling.

But what would 'similar' be for Gini and top 1. Not a 1 point move.

The main way of operationalising 'similar' is to look at Relative change: a percentage, rather than percentage point. We can put some threshold and see if there were rises or falls. 

No reason to expect this given the properties of the two measures. If we take lognormality we see... (MAke a chart in appendix - where we plot Gini against top 10 and top 1% assuming lognormality, and then add actual data for a particular country.) How unlognormal the top is would be another way to judge similarity. Rather than doing this, we bridge by aligning the indices.

- We also do absolute change: a percentage point. This is more intuitive. But somewhat arbitrary – differences in levels affect assessment of differences in trends.


- A third way is residuals from a regression of the two measures
    - This we will use to see countries that are particular outliers.





## Global data on inequality

### Global databases

A global view faces the hard limitation of the underlying data. This has two sides: firstly is there any data? Secondly the comparability of the data, across countries and over time.

Much improved – *harmonized* secondary databases. Three of note.

- PIP

- WID

- LIS



### Two worlds of inequality measurement



#### Connecting up the worlds is valuable

- for Policy
- for academic research


## Triangulating a global view


### Since 1990



### Since 1980




### Comparing metrics

Does it make a difference whether we look at Gini or top 10%?

People worry about whether Gini masks what's happening at the top.

Empirically: 
    - Make a linear model of top 10% on Gini, for each source separately
    - Make predicted top 10%
    - Take a look at the R2
    - Investigate individual countries with very poor predictions

Sub-Saharan Africa: example where the Gini fell in more cases than the top 10%.

### Since 1990


Similarities:

Convergence – Smaller rises in coutries that started out with high inequality. Driven regionally. (We could do a test for this.)

Indeed for some regions very similar picture:

    - MENA - Roughly 2 point fall, both Gini and top 10%. Only one country with a rise: Not total agreeement on coverage (one country either side)

    - South and South East Asia – Very similar not weighting by population. But wildly different when weighting by population, due to the much much stronger rise

    -  Sub-Saharan Afric – Very similar across sources. Top 10: Roughly even mix of rises and falling countries, but with a 3 point fall on average. Gini: More falls, 5 point on average. (Mention data quality issues: e.g. Kenya big fall. Lesoto big fall. But how comparable are the surveys?? Same surveys underlie WID...)

    - Western Europe – Rises in a majority of countries, but relatively moderate of 1-2 points (Whether Gini of top 10).


Differences:

Verry different bottom line at the global level:

- PIP: roughly equal numbers falling and rising. 0 average change – though a modest rise when pop weighted (2 points). Same whether Gini or Top 10. That's without LAtin America (Which WID is missing). Includung LatAm tips nudges it (with about a 1 point fall unweighter and 1 point rise weighted)

- WID: Far more countries with rising inequality. On average a 3 point rise (whether top 10 or Gini) – [Better to express these relative to the level of ineq. i.e. % increase rather than % point increase? A point rise means 'less' in WID terms because inequality levels are much higher.] But the most stark difference comes when we weight by population. Some key populous countries: India, China, US?, Indonesia? Russia 

That difference is driven by particular regions:
- 


More countries with rises. LArger rises. Especially larger populations. Average view very different:





Countries where the sources paint a radically different picture that affect the aggregate results:

- India: Insane rise in WID 34->56
- China:
- Russia: Massive drop in PIP. Insane rise in WID.
- USA: Much larger rise in WID.

What explains the different trends in these countries? (We can maybe look in more detail, at different welfare concepts etc.)

It sometimes goes the other way: Indonesia – Rise in PIP, fall in WID.

:::

#### Method 2: Use a regression to obtain the time trend



### Results for a range of inequality metrics


::: {.callout-note collapse="true" appearance="minimal"} 
## Calculations for comparisons



## Explaining differences between PIP and WID data

### For a subset of countries we can bridge between the PIP and WID data

Besides the underlying data sources, there are many differences between what is being measured in the PIP and WID data - notably the welfare concept and unit of analysis/equivalization.

In order to get a better understanding of where differences between the datasets arise, for a subset of countries we can bridge between the two somewhat. For example:

-   WID has post-tax income series for some countries
-   We can use LIS to look at how changing the welfare concept, unit of analysis, equivalisation affects things. (For equivalisation, we could also possibly use the newly available PIP harmonized microdata).

### More in-depth discussion of particular outliers

-   Russia is a very notable case where the two datasets tell very different stories.

# Conclusion
